version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: php/Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
      - ./php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
    restart: always
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: http://localhost/phpmyadmin/
    depends_on:
      - db
    volumes:
      - /sessions